set(CMAKE_CONFIGURATION_TYPES "Debug;Profile;Release" CACHE INTERNAL "" FORCE)
set(CMAKE_DEBUG_POSTFIX "d" CACHE INTERNAL "" FORCE)

set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "CMakeTools")
